language: php

# keep verisions minimal to limit total
# builds on free service. politeness.
php:
#    - "5.4"
    - "5.3"

services:
    - mysql

branches:
    only:
        - fannieDevelop

# test both msyqli and PDO 
# using deprecated mysql should really
# be discoutraged
env:
    - DB_DRIVER=pdo_mysql
    - DB_DRIVER=mysqli

before_install:
    - mysql -u root -e "DROP DATABASE IF EXISTS unit_test_op;"
    - mysql -u root -e "DROP DATABASE IF EXISTS unit_test_trans;"
    - mysql -u root -e "DROP DATABASE IF EXISTS unit_test_archive;"
install:
    # create Fannie databases
    - mysql -u root -e "CREATE DATABASE unit_test_op;"
    - mysql -u root -e "CREATE DATABASE unit_test_trans;"
    - mysql -u root -e "CREATE DATABASE unit_test_archive;"
    - mysqldump -u root unit_test_archive
    # create default configuration file
    - cp fannie/config.php.dist fannie/config.php
    # add path options
    - echo "\$FANNIE_ROOT = '"`pwd`"/fannie/';" >> fannie/config.php
    - echo "\$FANNIE_URL = '/fannie/';" >> fannie/config.php
    # add database options
    - echo "\$FANNIE_SERVER = '127.0.0.1';" >> fannie/config.php
    - echo "\$FANNIE_SERVER_USER = 'root';" >> fannie/config.php
    - echo "\$FANNIE_SERVER_PW = '';" >> fannie/config.php
    - echo "\$FANNIE_OP_DB = 'unit_test_op';" >> fannie/config.php
    - echo "\$FANNIE_TRANS_DB = 'unit_test_trans';" >> fannie/config.php
    - echo "\$FANNIE_ARCHIVE_DB = 'unit_test_archive';" >> fannie/config.php
    - echo "\$FANNIE_ARCHIVE_METHOD = 'partitions';" >> fannie/config.php
    # set database driver based on environment variable
    - echo "\$FANNIE_SERVER_DBMS = '$DB_DRIVER';" >> fannie/config.php

script:
    # Fannie tests
    # This must run first
    - phpunit --bootstrap fannie/unit-tests/bootstrap.php fannie/unit-tests/InstallTest.php
    # These can run in any order
    - phpunit --bootstrap fannie/unit-tests/bootstrap.php fannie/unit-tests/ItemsTest.php
    - phpunit --bootstrap fannie/unit-tests/bootstrap.php fannie/unit-tests/MembersTest.php
    - phpunit --bootstrap fannie/unit-tests/bootstrap.php fannie/unit-tests/PagesTest.php
    - phpunit --bootstrap fannie/unit-tests/bootstrap.php fannie/unit-tests/PluginsTest.php
    - phpunit --bootstrap fannie/unit-tests/bootstrap.php fannie/unit-tests/SQLManagerTest.php
    - phpunit --bootstrap fannie/unit-tests/bootstrap.php fannie/unit-tests/TasksTest.php
