language: php

# keep verisions minimal to limit total
# builds on free service. politeness.
php:
    - "5.6"
#    - "5.3"

services:
    - mysql

sudo: false

branches:
    only:
        - master

addons:
    code_climate:
        repo_token: 461be60a44fc2293c80a05712a1aa18ff7d12effec9a806d7722435b12ea2bbe

# test both msyqli and PDO 
env:
    matrix:
        - DB_DRIVER=pdo_mysql
#        - DB_DRIVER=mysqli

install:
    - sh fannie/unit-tests/travis-init.sh
    - sh pos/is4c-nf/unit-tests/travis-init.sh
    # limit package installation to codeclimate
    - rm composer.json
    - composer init -n
    - composer require codeclimate/php-test-reporter
    - mkdir -p build/logs

script:
    - TRAVISCI=true phpunit -c phpunit.xml

after_script:
    - vendor/bin/test-reporter

